
const ui = {
    r: document.getElementById("r"),
    x0: document.getElementById("x0"),
    minFrq: document.getElementById("minFrq"),
    maxFrq: document.getElementById("maxFrq"),
    bpm: document.getElementById("bpm"),
    waveType: document.getElementById("waveType"),
    saveLocalStorage: document.getElementById("saveLocalStorageButton"),
    deleteLocalStorage: document.getElementById("deleteLocalStorageButton"),
    localStorage: document.getElementById("localStorage"),
    loadInput: document.getElementById("loadInput"),
    playStop: document.getElementById("playStop"),
    frequencyMapSliders: [
        document.getElementById("frequency_00"),
        document.getElementById("frequency_01"),
        document.getElementById("frequency_02"),
        document.getElementById("frequency_03"),
        document.getElementById("frequency_04"),
        document.getElementById("frequency_05"),
        document.getElementById("frequency_06"),
        document.getElementById("frequency_07"),
        document.getElementById("frequency_08"),
        document.getElementById("frequency_09"),
        document.getElementById("frequency_10"),
    ],
    frequencyChart: document.getElementById("frequencyChart"),
};
